Repository codesquad-2023-group04/issue-tracker, pull requests merged in 2023-05, with the labels that each got.

#32 FEAT: 아이콘 이미지 첨부, 컴포넌트 생성 (#16)
  FE/package-lock.json
  FE/package.json
  FE/src/App.js
  FE/src/assets/Icon.js
  FE/src/assets/svgs/alertCircle.svg
  FE/src/assets/svgs/archive.svg
  FE/src/assets/svgs/calendar.svg
  FE/src/assets/svgs/checkBoxActive.svg
  FE/src/assets/svgs/checkBoxDisable.svg
  FE/src/assets/svgs/checkBoxInitial.svg
  FE/src/assets/svgs/checkOffCircle.svg
  FE/src/assets/svgs/checkOnCircle.svg
  FE/src/assets/svgs/chevronDown.svg
  FE/src/assets/svgs/edit.svg
  FE/src/assets/svgs/index.js
  FE/src/assets/svgs/label.svg
  FE/src/assets/svgs/logotypeLarge.svg
  FE/src/assets/svgs/logotypeLargeDark.svg
  FE/src/assets/svgs/milestone.svg
  FE/src/assets/svgs/paperclip.svg
  FE/src/assets/svgs/plus.svg
  FE/src/assets/svgs/search.svg
  FE/src/assets/svgs/smile.svg
  FE/src/assets/svgs/xSquare.svg
  FE/src/index.js
Labels: FE

#36 Fe feature/#19 add button
  FE/src/App.js
  FE/src/components/Button.js
  FE/src/components/TabButton.js
  FE/src/components/filterBar/FilterBar.js
  FE/src/components/issueList/IssueListHeader.js
  FE/src/mocks/mockIssueData.json
  FE/src/pages/IssueList.js
  FE/src/styles/color.js
Labels: FE, Feature

#43 Be feature/#10 issue list
  BE/build.gradle
  BE/src/main/java/issuetracker/issuetracker/domain/issue/IssueController.java
  BE/src/main/resources/application.yml
Labels: BE, Setting

#50 Fe feature/#45 add text input
  FE/src/App.js
  FE/src/components/Header.js
  FE/src/components/button/Button.js
  FE/src/components/button/buttonConstant.js
  FE/src/components/filterSection/FilterBar.js
  FE/src/components/filterSection/FiterSection.js
  FE/src/components/filterSection/TabButton.js
  FE/src/components/newIssue/NewIssueContainer.js
  FE/src/components/newIssue/NewIssueContent.js
  FE/src/components/newIssue/NewIssueFooter.js
  FE/src/components/newIssue/Sidebar.js
  FE/src/components/newIssue/TextInput.js
  FE/src/pages/NewIssue.js
  FE/src/styles/theme.js
Labels: FE

#49 Be feature/#10 issue list main page
  BE/src/main/java/issuetracker/issuetracker/domain/issue/Assignee.java
  BE/src/main/java/issuetracker/issuetracker/domain/issue/Issue.java
  BE/src/main/java/issuetracker/issuetracker/domain/issue/LabelRef.java
  BE/src/main/java/issuetracker/issuetracker/domain/issue/User.java
  BE/src/main/java/issuetracker/issuetracker/domain/issue/dto/InformationOfAssigneeInIssue.java
  BE/src/main/java/issuetracker/issuetracker/domain/issue/dto/InformationOfAuthorInIssue.java
  BE/src/main/java/issuetracker/issuetracker/domain/issue/dto/InformationOfLabelInIssueResponse.java
  BE/src/main/java/issuetracker/issuetracker/domain/issue/dto/MilestoneResponse.java
  BE/src/main/java/issuetracker/issuetracker/domain/issue/dto/req/IssueDTO.java
  BE/src/main/java/issuetracker/issuetracker/domain/issue/dto/req/IssueInfoReq.java
  BE/src/main/java/issuetracker/issuetracker/domain/issue/mapper/IssueRowMapper.java
  BE/src/main/java/issuetracker/issuetracker/domain/issue/repositroy/IssueRepositoryJDBCtem.java
  BE/src/main/java/issuetracker/issuetracker/domain/issue/service/IssueService.java
  BE/src/main/java/issuetracker/issuetracker/domain/issue/service/MilestoneinfoIssue.java
  BE/src/main/java/issuetracker/issuetracker/domain/label/dto/LabelDTO.java
  BE/src/main/java/issuetracker/issuetracker/domain/milestone/Milestone.java
  BE/src/main/java/issuetracker/issuetracker/domain/page/PageController.java
  BE/src/main/java/issuetracker/issuetracker/domain/page/PageRepository.java
  BE/src/main/java/issuetracker/issuetracker/domain/page/PageService.java
  BE/src/main/java/issuetracker/issuetracker/domain/page/dto/CountInfo.java
  BE/src/main/java/issuetracker/issuetracker/domain/page/dto/MainPage.java
  BE/src/main/java/issuetracker/issuetracker/domain/user/dto/AuthorDTO.java
  BE/src/main/resources/application.yml
Labels: BE, Feature

#53 FEAT: text area 컴포넌트 생성 (#39)
  FE/src/components/newIssue/NewIssueContent.js
  FE/src/components/newIssue/TextArea.js
  FE/src/components/newIssue/TextInput.js
Labels: FE, Feature

#61 ADD: 변수명을 일관되게 변경 (#27)
  BE/src/main/java/issuetracker/issuetracker/domain/issue/dto/IssueDTO.java
  BE/src/main/java/issuetracker/issuetracker/domain/issue/dto/IssueDetailInfoDTO.java
  BE/src/main/java/issuetracker/issuetracker/domain/issue/mapper/IssueRowMapper.java
  BE/src/main/java/issuetracker/issuetracker/domain/user/dto/AuthorDTO.java
Labels: BE, Refactoring

#73 FEAT: 버튼 컴포넌트 스타일 변경 (#65)
  FE/src/assets/Icon.js
  FE/src/components/button/Button.js
  FE/src/components/dropdown/Dropdown.js
  FE/src/components/filterSection/FiterSection.js
  FE/src/components/filterSection/TabButton.js
  FE/src/components/issueList/IssueListHeader.js
  FE/src/components/newIssue/NewIssueFooter.js
  FE/src/components/newIssue/Sidebar.js
Labels: FE

#84 Fe feature/#76 change text input
  FE/src/components/dropdown/Dropdown.js
  FE/src/components/dropdown/DropdownPanel.js
  FE/src/components/dropdown/DropdownPanelItem.js
  FE/src/components/filterSection/FilterBar.js
  FE/src/components/newIssue/NewIssueContent.js
  FE/src/components/newIssue/Sidebar.js
  FE/src/components/textForm/TextArea.js
  FE/src/components/textForm/TextInput.js
Labels: FE, Feature

#88 FEAT: 로그인 페이지 구현 (#87)
  FE/src/App.js
  FE/src/components/button/Button.js
  FE/src/components/newIssue/NewIssueContainer.js
  FE/src/components/newIssue/NewIssueContent.js
  FE/src/components/newIssue/NewIssueFooter.js
  FE/src/components/newIssue/Sidebar.js
  FE/src/components/textForm/TextArea.js
  FE/src/components/textForm/TextInput.js
  FE/src/pages/Login.js
  FE/src/pages/NewIssue.js
Labels: FE

#92 Fe feature/#91 add mock
  FE/src/App.js
  FE/src/components/button/Button.js
  FE/src/components/dropdown/Dropdown.js
  FE/src/components/dropdown/DropdownPanel.js
  FE/src/components/dropdown/DropdownPanelItem.js
  FE/src/components/dropdown/DropdownTabs.js
  FE/src/components/newIssue/NewIssueContainer.js
  FE/src/components/newIssue/NewIssueFooter.js
  FE/src/components/newIssue/Sidebar.js
  FE/src/mocks/handlers.js
  FE/src/mocks/labelData.json
  FE/src/mocks/milestoneData.json
  FE/src/mocks/userData.json
  FE/src/pages/Auth.jsx
  FE/src/pages/Login.js
  FE/src/pages/NewIssue.js
  FE/src/utils/fetch.js
Labels: FE

#85 Be refactor/#30 issue filter
  BE/src/main/java/issuetracker/issuetracker/domain/issue/repository/IssueRepository.java
  BE/src/main/java/issuetracker/issuetracker/domain/issue/service/IssueFilterService.java
  BE/src/main/java/issuetracker/issuetracker/domain/issue/service/IssueService.java
  BE/src/main/java/issuetracker/issuetracker/domain/label/LabelController.java
  BE/src/main/java/issuetracker/issuetracker/domain/label/LabelRepository.java
  BE/src/main/java/issuetracker/issuetracker/domain/label/LabelService.java
  BE/src/main/java/issuetracker/issuetracker/domain/milestone/MileRepository.java
  BE/src/main/java/issuetracker/issuetracker/domain/milestone/MilestoneService.java
  BE/src/main/java/issuetracker/issuetracker/domain/page/PageController.java
  BE/src/main/java/issuetracker/issuetracker/domain/page/PageFilterService.java
  BE/src/main/java/issuetracker/issuetracker/domain/user/UserController.java
  BE/src/main/java/issuetracker/issuetracker/domain/user/UserRepository.java
  BE/src/main/java/issuetracker/issuetracker/domain/user/UserService.java
  BE/src/main/java/issuetracker/issuetracker/domain/user/dto/UserFilterDTO.java
  BE/src/test/java/issuetracker/issuetracker/domain/issue/repository/IssueMyBatisRepositoryTest.java
  BE/src/test/java/issuetracker/issuetracker/domain/label/LabelServiceTest.java
  BE/src/test/java/issuetracker/issuetracker/domain/milestone/MilestoneServiceTest.java
  BE/src/test/java/issuetracker/issuetracker/domain/user/UserControllerTest.java
Labels: BE, Test

#107 CHORE: 코드 수정 완료
  FE/src/App.js
  FE/src/assets/Icon.js
  FE/src/components/Header.js
  FE/src/components/filterSection/FilterBar.js
  FE/src/components/filterSection/TabButton.js
  FE/src/components/issueDetail/CommentElements.jsx
  FE/src/components/issueDetail/IssueDetailContainer.jsx
  FE/src/components/issueDetail/IssueDetailContent.jsx
  FE/src/components/issueDetail/IssueDetailHeader.jsx
  FE/src/components/issueDetail/IssueDetailSideBar.jsx
  FE/src/components/newIssue/NewIssueContent.js
  FE/src/components/newIssue/NewIssueFooter.js
  FE/src/components/textForm/TextArea.js
  FE/src/pages/Auth.js
  FE/src/pages/IssueDetail.js
  FE/src/pages/IssueList.js
  FE/src/pages/Login.js
  FE/src/pages/NewIssue.js
Labels: FE

#111 Fe feature/#108 login error
  FE/src/components/issueDetail/IssueDetailHeader.jsx
  FE/src/components/textForm/TextInput.js
  FE/src/mocks/assigneeFilterData.json
  FE/src/mocks/authFilterData.json
  FE/src/mocks/closeFilterData.json
  FE/src/mocks/commentFilterData.json
  FE/src/mocks/handlers.js
  FE/src/mocks/labelsFilterData.json
  FE/src/mocks/milestonFilterData.json
  FE/src/mocks/openFilterData.json
  FE/src/mocks/userData.json
  FE/src/pages/Login.js
Labels: FE

#118 Fe feature/#97 issue detail
  FE/src/assets/svgs/grip.svg
  FE/src/assets/svgs/index.js
  FE/src/assets/svgs/trash.svg
  FE/src/components/LabelTag.js
  FE/src/components/button/Button.js
  FE/src/components/issueDetail/CommentElements.jsx
  FE/src/components/issueDetail/IssueDetailContainer.jsx
  FE/src/components/issueDetail/IssueDetailContent.jsx
  FE/src/components/issueDetail/IssueDetailHeader.jsx
  FE/src/components/issueDetail/IssueDetailSideBar.jsx
  FE/src/components/newIssue/NewIssueContainer.js
  FE/src/components/newIssue/NewIssueContent.js
  FE/src/components/newIssue/NewIssueFooter.js
  FE/src/components/textForm/TextArea.js
  FE/src/components/textForm/TextInput.js
  FE/src/mocks/commentData.json
  FE/src/pages/Login.js
Labels: FE, Feature

#128 Be feature/#116 oauth login
  BE/build.gradle
  BE/src/main/java/issuetracker/issuetracker/domain/user/login/JwtUtil.java
  BE/src/main/java/issuetracker/issuetracker/domain/user/login/LoginController.java
  BE/src/main/java/issuetracker/issuetracker/domain/user/login/LoginService.java
  BE/src/main/java/issuetracker/issuetracker/domain/user/login/OAuthConst.java
  BE/src/main/java/issuetracker/issuetracker/domain/user/login/dto/GithubToken.java
  BE/src/main/java/issuetracker/issuetracker/domain/user/login/dto/JWTResponse.java
  BE/src/main/java/issuetracker/issuetracker/domain/user/login/dto/UserProfileResponse.java
  BE/src/main/resources/static/index.html
Labels: BE, Feature

#133 FEAT: 상세 페이지 코멘트 기능 완료
  FE/src/components/PageHeader.js
  FE/src/components/issueDetail/CommentElements.jsx
  FE/src/components/issueDetail/IssueDetailContainer.jsx
  FE/src/components/issueDetail/IssueDetailHeader.jsx
  FE/src/components/textForm/IconTextInput.js
  FE/src/components/textForm/TextArea.js
  FE/src/index.js
  FE/src/pages/Auth.js
  FE/src/pages/Login.js
  FE/src/pages/NewIssue.js
  FE/src/utils/fetch.js
Labels: FE, Feature
